# need to set sudo vim /etc/ansible/hosts [assess1] amz-ec2 ip info
---
- hosts: assess1
  become: yes
  remote_user: ec2-user
  become_user: root
  tasks:
    - name: Download Long Term Jenkins release
      get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo

    - name: Import jenkins key from url
      ansible.builtin.rpm_key:
        state: present
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key

    - name: yum update
      yum:
        name: "*"
        state: latest

    - name: Install Java Requirements
      yum:
        name: java-11
      become: yes

    - name: Install jenkins
      yum:
        name: jenkins
        state: latest

    - name: daemon-reload to pick up config changes
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Start jenkins
      ansible.builtin.systemd:
        name: jenkins
        state: started

    - name: Install pip3s
      yum:
        name: python3-pip
      become: yes